### PR TITLE
use addon-test-support and provide a setup method for new testing API

### PR DESCRIPTION
**Pull request by jelhan**

### CODE REVIEW

**Comment by samselikoff** [comment]
nice work @jelhan! Would love to see this merged

**Comment by samselikoff** [comment]
In the meantime is there any way to use public APIs to get custom-assertions working with new-style tests?

**Comment by samselikoff** [comment]
Thank you!

**Comment by jelhan** [comment]
@snewcomer Any change to get this one merged?

**Comment by jelhan** [comment]
Thanks a lot for that quick response!

**Comment by snewcomer** [comment]
0.2.0 published!

**Pull request merged**
