### PR TITLE
Adds ember-string-utils for the blueprint.

### PR DESCRIPTION
**Pull request by patrickberkeley**
Fixes https://github.com/DockYard/ember-cli-custom-assertions/issues/13

### CODE REVIEW

**Comment by patrickberkeley** [comment]
This was already fixed but not unreleased https://github.com/DockYard/ember-cli-custom-assertions/pull/15

**Comment by patrickberkeley** [comment]
Actually, I'm reopening this because #15 doesn't add the dependency. Sorry for going back and forth.

**Comment by patrickberkeley** [comment]
And closing again... My local dependencies were cached.

**Comment by bcardarella** [comment]
I can cut a patch release but our goal is to align with https://github.com/emberjs/rfcs/pull/119

**Comment by bcardarella** [comment]
Released `0.0.5`

**Comment by patrickberkeley** [comment]
Ah, thanks for the info!

**Pull request closed without merging**
