### PR TITLE
README.md: clarification on import path, fixes #8

### LINKED ISSUE #8: Importing assertionInjector disables the whole test module
Simply doing 

```
import { assertionInjector } from '../assertions';
```

results in the whole module disappearing from QUnit test results.

Imgur

### PR DESCRIPTION
**Pull request by lolmaus**

### CODE REVIEW

**Comment by bcardarella** [comment]
Its probably better to just remove the relative path reference in the README and go with this absolute path

**Comment by rwjblue** [comment]
@bcardarella - Ya, only issue is that the absolute path embeds the app name (which can change).  I need to add a `addon-test-support` tree to Ember CLI so that it can just be `import { stuff } from 'ember-cli-custom-assertions';` which is what we really want.

**Comment by rwjblue** [comment]
We could make it work by moving these into `addon/` folder, and making the `treeForAddon` return false if we aren't including tests (aka during a production build).

**Comment by bcardarella** [comment]
@rwjblue ideally I'd just like to add this functionality to ember-cli-qunit and do away with the setup/teardown injections :wink:

**Pull request merged**
