### PR TITLE
update project

### PR DESCRIPTION
**Pull request by miguelcobain**
## Changes proposed in this pull request
- update project using ember-cli-update
- remove travis and add GH actions

This might be a first step towards #46 

Edit:
I pointed ember-leaflet tests to my ember-cli-custom-assertions fork and tests are running great!

### CODE REVIEW

**Review by snewcomer — APPROVED** [review]
Very nice

**Comment by miguelcobain** [comment]
@snewcomer can this be merged?
Happy new year! :)

**Comment by snewcomer** [comment]
@cibernox or @jleja would have to be the ones to hit that button and release!

**Comment by miguelcobain** [comment]
Updated to ember-cli 4.1.0 blueprint

**Review by jleja — APPROVED** [review]
Looks great, thanks for the contribution!

**Pull request merged**
